[package]
authors = ["Kornel <kornel@geekhood.net>"]
categories = ["development-tools::cargo-plugins", "development-tools::build-utils", "command-line-utilities"]
description = "Make Xcode project files from Cargo projects"
documentation = "https://gitlab.com/kornelski/cargo-xcode/blob/master/README.md#requirements"
homepage = "https://crates.rs/crates/cargo-xcode"
keywords = ["cargo", "subcommand", "xcode", "project"]
license = "MIT"
name = "cargo-xcode"
readme = "README.md"
repository = "https://gitlab.com/kornelski/cargo-xcode"
version = "1.1.0"

[dependencies]
cargo_metadata = "0.5.6"
getopts = "0.2.15"
sha1 = "0.6.0"
